networks:
  mcp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/27
          gateway: 192.168.100.1

services:
  # DIFFERENT MCP SERVERS - Using mcp-streamablehttp-proxy to wrap stdio servers

  # Everything MCP Server (Reference Implementation) - Port 3000
  everything-mcp:
    image: node:20-alpine
    container_name: everything-mcp
    ports:
      - "3000:3000"
    command: ["npx", "-y", "@modelcontextprotocol/server-everything", "streamableHttp", "--port", "3000", "--host", "0.0.0.0"]
    networks:
      mcp-network:
        ipv4_address: 192.168.100.2
    restart: unless-stopped

  # Filesystem MCP Server (File Operations) via Python Proxy - Port 3001  
  filesystem-mcp:
    image: python:3.11-alpine
    container_name: filesystem-mcp
    ports:
      - "3001:3001"
    command: sh -c "pip install mcp-streamablehttp-proxy && mcp-streamablehttp-proxy --host 0.0.0.0 --port 3001 npx @modelcontextprotocol/server-filesystem /tmp"
    networks:
      mcp-network:
        ipv4_address: 192.168.100.3
    restart: unless-stopped

  # Git MCP Server (Version Control) via Python Proxy - Port 3002
  git-mcp:
    image: python:3.11-alpine
    container_name: git-mcp
    ports:
      - "3002:3002"
    command: sh -c "apk add --no-cache git nodejs npm && pip install mcp-streamablehttp-proxy && mcp-streamablehttp-proxy --host 0.0.0.0 --port 3002 npx mcp-server-git"
    networks:
      mcp-network:
        ipv4_address: 192.168.100.4
    restart: unless-stopped

  # Memory MCP Server (Knowledge Graph) via Node.js Proxy - Port 3003
  memory-mcp:
    image: node:20-alpine
    container_name: memory-mcp
    ports:
      - "3003:3003"
    command: sh -c "npm install -g mcp-proxy && mcp-proxy --port 3003 --server stream --endpoint /mcp -- npx @modelcontextprotocol/server-memory"
    networks:
      mcp-network:
        ipv4_address: 192.168.100.5
    restart: unless-stopped

  # Gateway for routing and service discovery
  mcp-gateway:
    image: nginx:alpine
    container_name: mcp-gateway
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      mcp-network:
        ipv4_address: 192.168.100.10
    depends_on:
      - everything-mcp
      - filesystem-mcp
      - git-mcp
      - memory-mcp
    restart: unless-stopped 